Repository operate-first/support, pull requests merged in 2020-11, with the labels that each got.

#9 Update README
  README.md
Labels: size/S

#10 Add user documentation for JH
  README.md
  docs/user-docs/jupyterhub.md
Labels: size/S

#4 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/task.md
Labels: size/M

#11 Add ci, readme, and owners
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  LICENSE
  OWNERS
Labels: size/XL

#12 Fix link in README
  README.md
Labels: approved, size/XS
