Repository operate-first/support, pull requests merged in 2021-01, with the labels that each got.

#38 Add generic creds for Hue and Superset
  README.md
Labels: approved, documentation

#40 docs: Add onboarding docs for cluster-scoped resources
  .github/ISSUE_TEMPLATE/onboarding_to_cluster.md
  docs/onboarding_to_cluster.md
Labels: approved, size/L

#42 chore: Add issue template for Argo CD onboarding
  .github/ISSUE_TEMPLATE/onboarding_argocd.md
Labels: approved, do-not-merge/hold, size/M

#43 Add argocd onboarding docs
  .github/ISSUE_TEMPLATE/onboarding_argocd.md
  docs/onboarding_to_argocd.md
Labels: approved, size/L

#46 chore: Fix Onboard to a cluster guide link
  .github/ISSUE_TEMPLATE/onboarding_to_cluster.md
Labels: approved, size/XS

#50 docs: Add onboarding docs for sops
  docs/secret_management.md
Labels: approved, size/M

#49 docs: Add onboarding docs for rook
  docs/claiming_object_store.md
Labels: approved, size/M

#56 update wrong links that gives 404
  .github/ISSUE_TEMPLATE/onboarding_argocd.md
Labels: approved, size/XS
