Repository operate-first/support, pull requests merged in 2021-03, with the labels that each got.

#105 chore: Use .prow.yaml instead of .aicoe-ci.yaml
  .aicoe-ci.yaml
  .prow.yaml
Labels: approved, lgtm, size/S

#109 fix: Wrong link in S3 issue template
  .github/ISSUE_TEMPLATE/ceph_bucket_request.md
Labels: approved, lgtm, size/XS

#108 Update docs
  .prow.yaml
  docs/onboarding_to_argocd.md
Labels: approved, lgtm, size/M

#112 Update links to point to new zero cluster.
  README.md
Labels: approved, lgtm, size/XS

#115 chore: Rename hack to scripts folder
  docs/onboarding_to_cluster.md
Labels: approved, lgtm, size/XS

#118 docs: Use noobaa properly
  docs/claiming_object_store.md
Labels: approved, lgtm, size/XS

#125 Update generic password for hue/superset.
  README.md
Labels: approved, size/XS

#135 Clarify onboarding issue template.
  .github/ISSUE_TEMPLATE/onboarding_to_cluster.md
Labels: approved, size/M

#138 chore: Remove naved001 from OWNERS
  OWNERS
Labels: size/XS

#151 feat: Show the nice URL for a dashboard on the support readme
  README.md
Labels: approved, size/XS

#166 Update argocd docs and links to new location.
  docs/onboarding_to_argocd.md
Labels: approved, lgtm, size/M

#168 Rewrite cluster onboarding issue template
  .github/ISSUE_TEMPLATE/onboarding_to_cluster.md
Labels: approved, lgtm, size/M

#170 chore(prow): Lower CPU request
  .prow.yaml
Labels: approved, size/XS

#180 feature/onboarding project description
  .github/ISSUE_TEMPLATE/onboarding_to_cluster.md
Labels: approved, lgtm, size/S
