Repository operate-first/support, pull requests merged in 2021-07, with the labels that each got.

#301 Onboard Freeze Notice for template
  .github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml
Labels: approved, lgtm, size/XS

#317 feat: Add Rick
  README.md
Labels: approved, lgtm, size/S

#320 Add Trino+Superset User Guide
  docs/assets/images/cloudbeaver-db-view.png
  docs/assets/images/cloudbeaver-main-tab.png
  docs/assets/images/cloudbeaver-table-view.png
  docs/assets/images/superset-add-chart.png
  docs/assets/images/superset-add-dataset.png
  docs/assets/images/superset-barchart.png
  docs/assets/images/superset-dashboard-properties.png
  docs/assets/images/superset-dashboard.png
  docs/assets/images/superset-data-tab.png
  docs/assets/images/superset-export-dashboard.png
  docs/assets/images/superset-save-chart.png
  docs/assets/images/superset-save-dashboard.png
  docs/assets/images/superset-select-chart.png
  docs/assets/images/superset-visualizations.png
  docs/assets/images/trino-landing-page.png
  docs/assets/images/trino-query-page.png
  docs/trino_superset_user_guide.md
Labels: approved, lgtm, size/L
