Repository operate-first/support, pull requests merged in 2021-04, with the labels that each got.

#195 minor changes on support page
  README.md
  docs/assets/images/odh-dashboard.png
Labels: approved, lgtm, size/XS

#193 Add quota tiers doc.
  .github/ISSUE_TEMPLATE/onboarding_to_cluster.md
  docs/quotas.md
Labels: approved, lgtm, size/M

#200 Add x-small quota to docs
  docs/quotas.md
Labels: approved

#209 Update readme and odh/kubeflow docs.
  README.md
  docs/kubeflow/README.md
  docs/odh/README.md
  docs/onboarding_to_cluster.md
Labels: approved, lgtm, size/L

#212 Move Prometheus doc from support repo to apps repo
  docs/add_service_monitoring.md
Labels: approved, lgtm, size/M
