Repository operate-first/support, pull requests merged in 2021-02, with the labels that each got.

#66 docs: User data handling
  .github/ISSUE_TEMPLATE/ceph_bucket_request.md
  .github/ISSUE_TEMPLATE/pvc_request.md
  docs/user_profiles.md
Labels: approved, lgtm, size/M

#73 Add a section for adding users to argocd onboarding template
  .github/ISSUE_TEMPLATE/onboarding_argocd.md
Labels: approved, lgtm, size/S

#65 chore: Add issue template for general cluster scoped resource request
  .github/ISSUE_TEMPLATE/request_cluster_resources.md
Labels: approved, size/M

#74 Update owners file.
  OWNERS
Labels: approved, size/S

#82 make README more generic and add kubeflow apps in app list
  README.md
Labels: approved, lgtm, size/S

#95 Fix website URL
  README.md
Labels: approved, size/XS

#92 Added docs with instructions on adding monitoring to services
  docs/add_service_monitoring.md
Labels: approved, lgtm, size/M
