Repository operate-first/support, pull requests merged in 2021-11, with the labels that each got.

#444 Readme edits for smaug
  README.md
Labels: size/M, approved, lgtm

#455 Migrate docs to apps repo.
  .github/ISSUE_TEMPLATE/ceph_bucket_request.yaml
  .github/ISSUE_TEMPLATE/onboarding_argocd.yaml
  .github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml
  .github/ISSUE_TEMPLATE/pvc_request.yaml
  README.md
  docs/assets/images/cloudbeaver-db-view.png
  docs/assets/images/cloudbeaver-main-tab.png
  docs/assets/images/cloudbeaver-table-view.png
  docs/assets/images/moc-login.png
  docs/assets/images/odh-dashboard.png
  docs/assets/images/openshift-login.png
  docs/assets/images/superset-add-chart.png
  docs/assets/images/superset-add-dataset.png
  docs/assets/images/superset-barchart.png
  docs/assets/images/superset-dashboard-properties.png
  docs/assets/images/superset-dashboard.png
  docs/assets/images/superset-data-tab.png
  docs/assets/images/superset-export-dashboard.png
  docs/assets/images/superset-save-chart.png
  docs/assets/images/superset-save-dashboard.png
  docs/assets/images/superset-select-chart.png
  docs/assets/images/superset-visualizations.png
  docs/assets/images/trino-landing-page.png
  docs/assets/images/trino-query-page.png
  docs/claiming_object_store.md
  docs/intro.md
  docs/kubeflow/README.md
  docs/odh/README.md
  docs/onboarding_to_argocd.md
  docs/onboarding_to_cluster.md
  docs/quotas.md
  docs/secret_management.md
  docs/trino_superset_user_guide.md
  docs/user_profiles.md
Labels: size/XL, approved, lgtm

#471 Add uptdated quotas link for onboarding docs.
  .github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml
Labels: size/XS, approved, lgtm

#473 fix: Change description of area where you list users in the issue
  .github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml
Labels: size/XS, approved, lgtm
