Repository operate-first/support, pull requests merged in 2021-08, with the labels that each got.

#328 Add a template for requesting Python package index on Pulp
  .github/ISSUE_TEMPLATE/py_index_request.yaml
Labels: approved, lgtm, size/M

#336 Open source developer emphasis
  docs/intro.md
Labels: size/XS, approved, lgtm

#329 Fix outdated links in onboarding cluster doc.
  docs/onboarding_to_cluster.md
Labels: size/S

#325 chore: convert issue templates to issue forms, part 2
  .github/ISSUE_TEMPLATE/onboarding_argocd.md
  .github/ISSUE_TEMPLATE/onboarding_argocd.yaml
  .github/ISSUE_TEMPLATE/pvc_request.md
  .github/ISSUE_TEMPLATE/pvc_request.yaml
Labels: approved, size/L, lgtm

#355 Update outdated links to odh services.
  docs/odh/README.md
  docs/trino_superset_user_guide.md
Labels: size/M

#358 readme: update onboarding links
  README.md
Labels: size/XS, approved, lgtm, needs-ok-to-test
