Repository operate-first/support, pull requests merged in 2021-06, with the labels that each got.

#269 Fix typo in quota doc.
  docs/quotas.md
Labels: approved, size/XS

#270 remove ipolonsk from owners
  OWNERS
Labels: approved, lgtm, size/XS

#273 Update onboarding doc to use cli.
  docs/onboarding_to_cluster.md
Labels: approved, lgtm, size/S

#283 Support page improvements for users
  README.md
Labels: approved, lgtm, size/L

#285 Add issue template for kafka topics/users
  .github/ISSUE_TEMPLATE/kafka_user_topic_request.md
Labels: approved, size/M

#293 chore: Convert issue templates to issue forms, part 1
  .github/ISSUE_TEMPLATE/ceph_bucket_request.md
  .github/ISSUE_TEMPLATE/ceph_bucket_request.yaml
  .github/ISSUE_TEMPLATE/onboarding_to_cluster.md
  .github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml
  .pre-commit-config.yaml
  yamllint-config.yaml
Labels: approved, lgtm, size/L
