Repository operate-first/support, pull requests merged in 2021-05, with the labels that each got.

#225 chore: Remove martin from reviewers so he's not flooded by notifications
  OWNERS
Labels: approved, lgtm, size/XS

#232 Bring operate-first-workloads content to support
  docs/intro.md
Labels: approved, lgtm, size/M

#234 Update intro.md
  docs/intro.md
Labels: approved, lgtm, size/XS

#233 Clarify argocd onboarding instructions.
  docs/onboarding_to_argocd.md
Labels: approved, lgtm, size/S

#230 Update readme with monitoring restriction notice.
  README.md
Labels: approved, lgtm, size/XS

#238 Update onboarding cluster docs to reflect adr 15
  docs/onboarding_to_cluster.md
Labels: size/M
